

spring.application.name=ecoembes-server
spring.output.ansi.enabled=ALWAYS


server.port=8080


spring.datasource.url=jdbc:h2:file:./ecoembesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
external.plassb.base-url=http://localhost:8081/plassb

contsocket.base-url=http://localhost
contsocket.port=8083
